apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: fullstack-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: pvc

---

apiVersion: v1
kind: Service
metadata:
  namespace: fullstack-app
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
