apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    app: webapp
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: fullstack-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: "webapp"
      